/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/svr2112/challenge_problem_1/src/move_gripper/srv/CloseGripper.srv
 *
 */


#ifndef MOVE_GRIPPER_MESSAGE_CLOSEGRIPPER_H
#define MOVE_GRIPPER_MESSAGE_CLOSEGRIPPER_H

#include <ros/service_traits.h>


#include <move_gripper/CloseGripperRequest.h>
#include <move_gripper/CloseGripperResponse.h>


namespace move_gripper
{

struct CloseGripper
{

typedef CloseGripperRequest Request;
typedef CloseGripperResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CloseGripper
} // namespace move_gripper


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::move_gripper::CloseGripper > {
  static const char* value()
  {
    return "d4fee5f1f332a01373ae327878f67206";
  }

  static const char* value(const ::move_gripper::CloseGripper&) { return value(); }
};

template<>
struct DataType< ::move_gripper::CloseGripper > {
  static const char* value()
  {
    return "move_gripper/CloseGripper";
  }

  static const char* value(const ::move_gripper::CloseGripper&) { return value(); }
};


// service_traits::MD5Sum< ::move_gripper::CloseGripperRequest> should match 
// service_traits::MD5Sum< ::move_gripper::CloseGripper > 
template<>
struct MD5Sum< ::move_gripper::CloseGripperRequest>
{
  static const char* value()
  {
    return MD5Sum< ::move_gripper::CloseGripper >::value();
  }
  static const char* value(const ::move_gripper::CloseGripperRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::move_gripper::CloseGripperRequest> should match 
// service_traits::DataType< ::move_gripper::CloseGripper > 
template<>
struct DataType< ::move_gripper::CloseGripperRequest>
{
  static const char* value()
  {
    return DataType< ::move_gripper::CloseGripper >::value();
  }
  static const char* value(const ::move_gripper::CloseGripperRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::move_gripper::CloseGripperResponse> should match 
// service_traits::MD5Sum< ::move_gripper::CloseGripper > 
template<>
struct MD5Sum< ::move_gripper::CloseGripperResponse>
{
  static const char* value()
  {
    return MD5Sum< ::move_gripper::CloseGripper >::value();
  }
  static const char* value(const ::move_gripper::CloseGripperResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::move_gripper::CloseGripperResponse> should match 
// service_traits::DataType< ::move_gripper::CloseGripper > 
template<>
struct DataType< ::move_gripper::CloseGripperResponse>
{
  static const char* value()
  {
    return DataType< ::move_gripper::CloseGripper >::value();
  }
  static const char* value(const ::move_gripper::CloseGripperResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVE_GRIPPER_MESSAGE_CLOSEGRIPPER_H
