(cl:defpackage move_base-srv
  (:use )
  (:export
   "MOVEBASE"
   "<MOVEBASE-REQUEST>"
   "MOVEBASE-REQUEST"
   "<MOVEBASE-RESPONSE>"
   "MOVEBASE-RESPONSE"
   "ROTATEBASE"
   "<ROTATEBASE-REQUEST>"
   "ROTATEBASE-REQUEST"
   "<ROTATEBASE-RESPONSE>"
   "ROTATEBASE-RESPONSE"
  ))

