/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/svr2112/challenge_problem_1/src/move_base/srv/MoveBase.srv
 *
 */


#ifndef MOVE_BASE_MESSAGE_MOVEBASE_H
#define MOVE_BASE_MESSAGE_MOVEBASE_H

#include <ros/service_traits.h>


#include <move_base/MoveBaseRequest.h>
#include <move_base/MoveBaseResponse.h>


namespace move_base
{

struct MoveBase
{

typedef MoveBaseRequest Request;
typedef MoveBaseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveBase
} // namespace move_base


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::move_base::MoveBase > {
  static const char* value()
  {
    return "4d1b79b5a5ef1f221b7952b382ecb8cb";
  }

  static const char* value(const ::move_base::MoveBase&) { return value(); }
};

template<>
struct DataType< ::move_base::MoveBase > {
  static const char* value()
  {
    return "move_base/MoveBase";
  }

  static const char* value(const ::move_base::MoveBase&) { return value(); }
};


// service_traits::MD5Sum< ::move_base::MoveBaseRequest> should match 
// service_traits::MD5Sum< ::move_base::MoveBase > 
template<>
struct MD5Sum< ::move_base::MoveBaseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::move_base::MoveBase >::value();
  }
  static const char* value(const ::move_base::MoveBaseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::move_base::MoveBaseRequest> should match 
// service_traits::DataType< ::move_base::MoveBase > 
template<>
struct DataType< ::move_base::MoveBaseRequest>
{
  static const char* value()
  {
    return DataType< ::move_base::MoveBase >::value();
  }
  static const char* value(const ::move_base::MoveBaseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::move_base::MoveBaseResponse> should match 
// service_traits::MD5Sum< ::move_base::MoveBase > 
template<>
struct MD5Sum< ::move_base::MoveBaseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::move_base::MoveBase >::value();
  }
  static const char* value(const ::move_base::MoveBaseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::move_base::MoveBaseResponse> should match 
// service_traits::DataType< ::move_base::MoveBase > 
template<>
struct DataType< ::move_base::MoveBaseResponse>
{
  static const char* value()
  {
    return DataType< ::move_base::MoveBase >::value();
  }
  static const char* value(const ::move_base::MoveBaseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVE_BASE_MESSAGE_MOVEBASE_H
