/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/svr2112/challenge_problem_1/src/move_base/srv/RotateBase.srv
 *
 */


#ifndef MOVE_BASE_MESSAGE_ROTATEBASE_H
#define MOVE_BASE_MESSAGE_ROTATEBASE_H

#include <ros/service_traits.h>


#include <move_base/RotateBaseRequest.h>
#include <move_base/RotateBaseResponse.h>


namespace move_base
{

struct RotateBase
{

typedef RotateBaseRequest Request;
typedef RotateBaseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RotateBase
} // namespace move_base


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::move_base::RotateBase > {
  static const char* value()
  {
    return "194939c001a63802dc4131cae92cda22";
  }

  static const char* value(const ::move_base::RotateBase&) { return value(); }
};

template<>
struct DataType< ::move_base::RotateBase > {
  static const char* value()
  {
    return "move_base/RotateBase";
  }

  static const char* value(const ::move_base::RotateBase&) { return value(); }
};


// service_traits::MD5Sum< ::move_base::RotateBaseRequest> should match 
// service_traits::MD5Sum< ::move_base::RotateBase > 
template<>
struct MD5Sum< ::move_base::RotateBaseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::move_base::RotateBase >::value();
  }
  static const char* value(const ::move_base::RotateBaseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::move_base::RotateBaseRequest> should match 
// service_traits::DataType< ::move_base::RotateBase > 
template<>
struct DataType< ::move_base::RotateBaseRequest>
{
  static const char* value()
  {
    return DataType< ::move_base::RotateBase >::value();
  }
  static const char* value(const ::move_base::RotateBaseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::move_base::RotateBaseResponse> should match 
// service_traits::MD5Sum< ::move_base::RotateBase > 
template<>
struct MD5Sum< ::move_base::RotateBaseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::move_base::RotateBase >::value();
  }
  static const char* value(const ::move_base::RotateBaseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::move_base::RotateBaseResponse> should match 
// service_traits::DataType< ::move_base::RotateBase > 
template<>
struct DataType< ::move_base::RotateBaseResponse>
{
  static const char* value()
  {
    return DataType< ::move_base::RotateBase >::value();
  }
  static const char* value(const ::move_base::RotateBaseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVE_BASE_MESSAGE_ROTATEBASE_H
